# Estamos usando tbm o https://github.com/Huachao/vscode-restclient verificar exemplos que é possivel fazer com ele!

# @name: get welcome to API
GET http://localhost:3333/

###

# @name: get-all-prompts
GET http://localhost:3333/prompts

###

# @name: upload-video
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="exemple.mp3"
Content-Type: image/png

< ./exemple.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name: create-transcription
POST http://localhost:3333/videos/08909f9b-541f-4e9a-b827-eec038ededd6/transcription
Content-Type: application/json

{
    "prompt": "Redis"
}

