# Estamos usando tbm o https://github.com/Huachao/vscode-restclient verificar exemplos que é possivel fazer com ele!

# @name: get welcome to API
GET http://localhost:3333/

###

# @name: get-all-prompts
GET http://localhost:3333/prompts

###

# @name: get-api-opnai-status
GET http://localhost:3333/check-connection

###

# @name: upload-video
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="exemple.mp3"
Content-Type: image/png

< ./exemple.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name: create-transcription
POST http://localhost:3333/videos/49f311c6-3518-48fe-a614-a097781d1be8/transcription
Content-Type: application/json

{
    "prompt": "Rede Social"
}

